language: node_js
node_js:
  - "node"
install: yarn --cwd "${PACKAGE}" install
script:
  - |
    set -euo pipefail
    cd "${PACKAGE}"
    if [[ "${PACKAGE}" == "api" ]]; then
        yarn run lint
        yarn test
        yarn run build
    elif [[ "${PACKAGE}" == "core" ]]; then
        yarn test
    fi
    cd -
env:
  matrix:
    - PACKAGE=api
    - PACKAGE=core
cache: yarn
