language: node_js
node_js:
  - "node"
install:
  - |
    cd "${JOB}"
    if [[ "${JOB}" == "api" ]]; then
        yarn install
    fi
    cd -
script:
  - |
    cd "${JOB}"
    if [[ "${JOB}" == "api" ]]; then
        yarn run lint
        yarn test
        yarn run build
    elif [[ "${JOB}" == "core" ]]; then
        yarn test
    fi
    cd -
env:
  matrix:
    - JOB=api
    - JOB=core
cache: yarn
